import type {NextPage} from 'next'
import Head from 'next/head'
import Header from "../components/UI/Header/header";
import Main from "../components/UI/Main/main";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <script src="https://cdn.tailwindcss.com"/>
            </Head>
            <Header/>
            <Main/>
        </div>
    )
}

export default Home
